language: php
sudo: required
dist: trusty
php:
- 7.0
before_install:
- composer self-update
before_script:
- composer install --no-interaction
script:
- phpdbg -qrr vendor/bin/phpunit tests/
cache:
  directories:
  - vendor