language: php
sudo: required
dist: trusty
php:
- 7.1
- 7.2
- 7.3
before_install:
- composer self-update
before_script:
- composer install --no-interaction
script:
- php vendor/bin/phpunit --coverage-clover=coverage.xml
cache:
  directories:
  - vendor
after_success:
  - bash <(curl -s https://codecov.io/bash)
